---
workflow:
  rules:
    # Do not allow manually triggered pipelines to prevent duplicates!
    # Instead re-run the pipeline created with the last push
    - if: $CI_PIPELINE_SOURCE != "push"
      when: never
    # Only execute on push / merge to main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

default:
  interruptible: true

stages:
  - test
  - build
  - release

cache:
  key: default
  paths:
    - node_modules

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

node:build:
  stage: build
  image: docker.io/node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

container:release:
  stage: release
  image: quay.io/containers/buildah:latest
  before_script:
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - export CONTAINER_TAG=$(date +%Y-%m-%d)-ci${CI_PIPELINE_IID}
    - buildah build -t $CI_PROJECT_NAME:latest
    - buildah tag $CI_PROJECT_NAME:latest $CI_REGISTRY_IMAGE:${CONTAINER_TAG}-arm64
    - buildah tag $CI_PROJECT_NAME:latest $CI_REGISTRY_IMAGE:latest-arm64
    - buildah push $CI_REGISTRY_IMAGE:${CONTAINER_TAG}-arm64
    - buildah push $CI_REGISTRY_IMAGE:latest-arm64
